name: Build Julia Blogpost
description: Build a Julia blogpost using Literate.jl
runs:
  using: composite
  steps:
    - id: build
      name: Build blogpost
      shell: bash
      run: julia --project=. -e 'import BuildJuliaBlogpost; BuildJuliaBlogpost.build(run_pandoc=false, create_tarball=true)'
